import { Employee } from "./employee";

export const EMPLOYEES : Employee[]=[
    {
        fullName : "Alyvia Cope",
        firstName : "Alyvia",
        lastName : "Cope",
        phone : 9999900000,
        gender : "Female",
        age : 28,
        jobTitle : "Manager",
        yearsOfExperience : 9,
        salary : 2550000,
        department : "Management",
        id : 101,
        email : "alyvia.cope6@finhigh.com",
        grade : "A",
        image : "assets/images/female-icon.jpg",
    },
    {
        fullName : "Kinslee Fink",
        firstName : "Kinslee",
        lastName : "Fink",
        phone : 9888900000,
        gender : "Male",
        age : 26,
        jobTitle : "Cloud Architect",
        yearsOfExperience : 4,
        salary : 1250000,
        department : "IT",
        id : 102,
        email : "kinslee.fink7@y-corporation.com",
        grade : "B",
        image : "assets/images/male-icon.jpg",
    },
    {
        fullName : "Tyrone Lowe",
        firstName : "Tyrone",
        lastName : "Lowe",
        phone : 9777900000,
        gender : "Male",
        age : 31,
        jobTitle : "Network Administrator",
        yearsOfExperience : 3,
        salary : 1000000,
        department : "IT",
        id : 103,
        email : "tyrone.lowe6@warephase.com",
        grade : "B",
        image : "assets/images/male-icon.jpg",
    },
    {
        fullName : "Vivianna Kiser",
        firstName : "Vivianna",
        lastName : "Kiser",
        phone : 9666900000,
        gender : "Female",
        age : 28,
        jobTitle : "Sales Manager",
        yearsOfExperience : 3,
        salary : 1750000,
        department : "Sales",
        id : 104,
        email : "vivianna.kiser8@dontechi.com",
        grade : "A",
        image : "assets/images/female-icon.jpg",
    },
    {
        fullName : "Phoenix Baker",
        firstName : "Phoenix",
        lastName : "Baker",
        phone : 9555900000,
        gender : "Male",
        age : 32,
        jobTitle : "Computer Programmer",
        yearsOfExperience : 8,
        salary : 2600000,
        department : "IT",
        id : 105,
        email : "phoenix.baker7@konmatfix.com",
        grade : "C",
        image : "assets/images/male-icon.jpg",
    },
    {
        fullName : "Aaiden Savage",
        firstName : "Aaiden",
        lastName : "Savage",
        phone : 9988900000,
        gender : "Male",
        age : 26,
        jobTitle : "Computer Programmer",
        yearsOfExperience : 9,
        salary : 2500000,
        department : "IT",
        id : 106,
        email : "aaiden.savage6@faxquote.com",
        grade : "C",
        image : "assets/images/male-icon.jpg",
    },
    {
        fullName : "Marco Gregg",
        firstName : "Marco",
        lastName : "Gregg",
        phone : 9999900000,
        gender : "Male",
        age : 38,
        jobTitle : "Virtual Assistant",
        yearsOfExperience : 5,
        salary : 1250000,
        department : "Customer Service Job",
        id : 107,
        email : "marco.gregg5@plexzap.com",
        grade : "B",
        image : "assets/images/male-icon.jpg",
    },
    {
        fullName : "Kianna Pham",
        firstName : "Kianna",
        lastName : "Pham",
        phone : 9999900000,
        gender : "Female",
        age : 29,
        jobTitle : "Technical Specialist",
        yearsOfExperience : 3,
        salary : 1050000,
        department : "IT",
        id : 108,
        email : "kianna.pham6@scottech.com",
        grade : "D",
        image : "assets/images/female-icon.jpg",
    },

]